name: "Check installed files"
description: "Validates that the installed files are the ones expected and with the right stats"

inputs:
  expected_files:
    required: true
    description: "Path to the 'expected files' CSV file"
  report_file:
    required: false
    description: "Path to the report file"
    default: "/tmp/report.md"
  current_status:
    required: false
    description: "Path to the current status CSV file"
    default: "/tmp/current.csv"


runs:
  using: "composite"
  steps:
  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'

  - name: Create python virtual environment
    shell: bash
    run: |
      cd $GITHUB_ACTION_PATH
      python3 -m venv venv
      source venv/bin/activate
      pip3 install --upgrade pip
      pip3 install -r requirements.txt

  - name: Get the files stats
    shell: bash
    run: |
      cd ${GITHUB_ACTION_PATH}
      sudo venv/bin/python3 check_files.py -b '${{ inputs.current_status }}'

  - name: Upload current stats
    if: success()
    uses: actions/upload-artifact@v4
    with:
      name: current_stats
      path: ${{ inputs.current_status }}

  - name: Compare results
    shell: bash
    run: |
      cd ${GITHUB_ACTION_PATH}
      sudo venv/bin/python3 check_files.py --report '${{ inputs.report_file }}' --file_csv_path '${{ inputs.expected_files }}'

  - name: Upload validation results
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: validation_results
      path: ${{ inputs.report_file }}

  - name: Generate report
    if: always()
    shell: bash
    run: |
      cat ${{ inputs.report_file }} >> $GITHUB_STEP_SUMMARY
