run-name: Python code analysis for ${{ inputs.branch }}
name: Python code analysis

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to scan"
        required: true
        default: ""
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
        default: ""

jobs:
  bandit:
    name: Python static code analysis for ${{ inputs.branch }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkot the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Bandit Scan
        uses: PyCQA/bandit-action@v1
        with:
          exclude: .git,__pycache__,*/test_*,*/test/*,*/tests/*,*/testing/*
