name: Build Binutils Packages

on:
  workflow_dispatch:
    inputs:
      binutils_major_version:
        description: "Binutils major version"
        required: true
        default: "2"
      binutils_minor_version:
        description: "Binutils minor version"
        required: true
        default: "39"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t binutils-deb -f packages/debs/amd64/binutils/Dockerfile \
            --build-arg BINUTILS_MAJOR_VERSION=${{ github.event.inputs.binutils_major_version }} \
            --build-arg BINUTILS_MINOR_VERSION=${{ github.event.inputs.binutils_minor_version }} .
          docker run -v /tmp:/tmp binutils-deb /bin/bash -c "cp /packages/* /tmp/"

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: binutils-deb
          path: /tmp/*.deb

  build-rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t binutils-rpm -f packages/rpms/amd64/binutils/Dockerfile \
            --build-arg BINUTILS_MAJOR_VERSION=${{ github.event.inputs.binutils_major_version }} \
            --build-arg BINUTILS_MINOR_VERSION=${{ github.event.inputs.binutils_minor_version }} .
          docker run -v /tmp:/tmp binutils-rpm /bin/bash -c "cp /packages/* /tmp/"

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: binutils-rpm
          path: /tmp/*.rpm