name: Build GCC Packages

on:
  workflow_dispatch:
    inputs:
      gcc_url:
        description: "GCC source tarball URL"
        required: true
        default: "https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-15.1.0.tar.xz"

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t gcc-deb -f packages/debs/amd64/gcc/Dockerfile .
          docker run -it -v /tmp:/tmp gcc-deb /bin/bash -c "cp /packages/* /tmp/"

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-deb
          path: /tmp/*.deb

  build-rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t gcc-rpm -f packages/rpms/amd64/gcc/Dockerfile .
          docker run -it -v /tmp:/tmp gcc-rpm /bin/bash cp -c "/packages/* /tmp/"

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-rpm
          path: /tmp/*.rpm
