name: Legacy unit tests for wazuh agent

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch'
        required: true
        default: 'main'
  pull_request:
    paths:
        - "src/**"
        - ".github/workflows/legacy-unit-tests.yml"

jobs:
  Unit-Tests:
    strategy:
          fail-fast: false
          matrix:
              target: [agent, winagent]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: "Install dependencies"
        uses: ./.github/actions/install_build_deps
        with:
          target: ${{ matrix.target }}
      - name: "Build wazuh agent"
        uses: ./.github/actions/build_test_flags
        with:
          target: ${{ matrix.target }}
      - name: "Build wazuh agent legacy unit tests"
        uses: ./.github/actions/legacy_unit_tests_build
        with:
          target: ${{ matrix.target }}
      - name: "Run wazuh agent legacy unit tests"
        uses: ./.github/actions/legacy_unit_tests_run
        with:
          target: ${{ matrix.target }}
  Build-RPM-Manager:
      runs-on: ubuntu-22.04
      needs: Unit-Tests
      steps:
        - name: Build RPM Manager
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "packages-build-manager.yml",
                ref: "master",
                inputs: {
                  docker_image_tag: "auto",
                  architecture: "x86_64",
                  system: "rpm",
                  revision: "0",
                  is_stage: false,
                  debug: false,
                  checksum: false
                }
              });
